name: XcodeBuild

on:
  pull_request:
    branches: 
      - main

jobs:

  cleanBuild:
    name: Clean & Build
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 11']
    steps:
    - uses: actions/checkout@v2
    
    - name: Clean
      run: xcodebuild clean -project Github.xcodeproj -scheme Github -derivedDataPath Build/ -destination "${{ matrix.destination }}"

    - name: Build
      run: xcodebuild build -project Github.xcodeproj -scheme Github -derivedDataPath Build/ -destination "${{ matrix.destination }}"

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: Build/Build/Products/Debug-iphonesimulator/Github.app

  test:
    name: Test
    needs: cleanBuild
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 11']
    steps:
    - uses: actions/checkout@v2

    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: build
        path: Build/Build/Products/Debug-iphonesimulator/Github.app

    - name: Test
      run: xcodebuild test -project Github.xcodeproj -scheme GithubTests -derivedDataPath Build/ -destination "${{ matrix.destination }}"
    
